---
title: "competition-indices"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{competition-indices}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(RPackVGL)
```




```{r }


dtoto <- tabtoto_compet
sp_dtoto <- split(dtoto, dtoto$keysc)



#########################################
#########################################

#selection des fichiers de dtoto (2 jeux de simul dans tabtoto_compet)

key <- "55-1 Fix2-nonFixSimTest Lusignan30IrrN2 -"
keypur <- "55-1 nonFixSimTest-nonFixSimTest Lusignan30IrrN2 -" #traitement pur en plus

#key <-"88-1 Fix2-nonFixSimTest Lusignan30IrrN2 -"
#keypur <- "88-1 nonFixSimTest-nonFixSimTest Lusignan30IrrN2 -"

dat <- rbind(sp_dtoto[[key]], sp_dtoto[[keypur]])
dat$damier <- as.character(dat$damier)



#########################################
#########################################

#selection des donnees
scenar <- strsplit(key, ' ')[[1]][1]

pur1 <- dat[dat$densite2 == 0., ]
pur2 <- dat[dat$densite1 == 0., ]
iso1 <- pur1[pur1$densite ==min(pur1$densite) , ]
iso2 <- pur2[pur2$densite ==min(pur2$densite) , ]

densi <- 400.
diag <- dat[dat$densite == 400., ]
diag50 <- diag[diag$damier=="damier0" | diag$damier=="damier4" | diag$damier=="damier8",] #point 50/50
tribas <- dat[dat$densite <= 400., ] #triangle bas
trihaut <- dat[dat$densite >= 400., ] #triangle bas
one_one <- dat[dat$densite1 == dat$densite2, ]
all <- dat


#pur1
#plante qd fait des figures


# visu du plan de simulation des densite
#layout(matrix(1:8,2,4))
#layout fait planter le knit

plot(all$densite1, all$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=2, main ="all", xlim=c(0,400), ylim=c(0,400))
plot(tribas$densite1, tribas$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=2, main ="tribas", xlim=c(0,400), ylim=c(0,400))
plot(diag$densite1, diag$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=2, main ="diag", xlim=c(0,400), ylim=c(0,400))
plot(diag50$densite1, diag50$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=2, main ="diag50", xlim=c(0,400), ylim=c(0,400))
plot(one_one$densite1, one_one$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=2, main ="one_one", xlim=c(0,400), ylim=c(0,400))
plot(pur1$densite1, pur1$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=2, main ="pur1", xlim=c(0,400), ylim=c(0,400))
plot(pur2$densite1, pur2$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=2, main ="pur2", xlim=c(0,400), ylim=c(0,400))



#########################################
#########################################
#reponse densite pur

#fit des reponses pures sur donnees pures (a et beta)
#trace visu des reponses pures
x <- pur1
titre <- paste(strsplit(as.character(x$mix[1]), '-')[[1]][1], scenar)
res1 <- Calc_Beta_coeff(x)
Plt_Yresp_densite1(x, res1, main=titre, xlab="densite 1", ylab="Ytot")
#res1

x <- pur2
res2 <- Calc_Beta_coeff(x)
titre <- paste(strsplit(as.character(x$mix[1]), '-')[[1]][2], scenar)
res2 <- Calc_Beta_coeff(x)
Plt_Yresp_densite1(x, res2, main=titre, xlab="densite 1", ylab="Ytot")
#res2




#########################################
#########################################
#reponse effet voisin

#fit des reponses au voisin (gamma)


# fit peut etre fait sur differents jeu de donnees
x <- diag#tribas#diag50#all#trihaut#
# fit peut etre fait en forcant ou non les reponses a densite en pur
resg <- Calc_Gamma_coeffesp12(x, iso1, iso2, res1, res2)
#resg <- Calc_Gamma_coeffesp12(x, iso1, iso2, res1, res2,free=T) #sans forcage
parameters1 <- resg[["parameters1"]]
parameters2 <- resg[["parameters2"]]
resg

#trace la visu du fit sur diag
x <- diag
titre <- paste("400 ", scenar)
Plot_diag_respFitsd1d2(x, parameters1, parameters2, dmax=400., main=titre, xlab="densite diag", ylab="Ytot")


#trace la visu du fit surone_one
x <- one_one
titre <- paste("50/50 sowing", scenar)
Plot_OneOne_Resp_dtot(x, parameters1, parameters2, dmax=400., ylim=c(0,2300), main=titre, xlim=c(0, max(x$densite1+x$densite2)), xlab="densite one-one", ylab="Ytot")
Plot_OneOne_prop(x, parameters1, parameters2, dmax=400., main=titre, ylim=c(0,1), xlim=c(0, max(x$densite1+x$densite2)), xlab="densite one-one",ylab="sp prop")




### fit des autres indices
#calcul des autres coeff de competition
Sij <- Calc_Sij_coefficients(res1, res2, parameters1, parameters2)
Eij <- Calc_Eij_coefficients(res1, res2, parameters1, parameters2)
Rij <- Calc_Rij_coefficients(res1, res2, parameters1, parameters2)

Sij
Eij
Rij
#!! le calcul de ces indices se fait seulement pour free=F
#-> modif des fonction pour prendre bon a et beta si free=T?




###############
###############
# test competition intensity
x <- all
I_esp1 <- Calc_CompetitionIntensity(x$YEsp1, x$densite1, iso1$YEsp1/iso1$densite1)
I_esp2 <- Calc_CompetitionIntensity(x$YEsp2, x$densite2, iso2$YEsp2/iso2$densite2)
df = data.frame(x$densite1, x$densite2, I_esp1, I_esp2)

# plot des intensite de competition

I_esp1[is.nan(I_esp1)] <- 0.
I_esp2[is.nan(I_esp2)] <- 0.

# taille cex proportionnelle a intensite
plot(x$densite1, x$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=2*I_esp1, main ="Competition Intensity esp 1", xlim=c(0,400), ylim=c(0,400))
plot(x$densite1, x$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=2*I_esp2, main ="Competition Intensity esp 2", xlim=c(0,400), ylim=c(0,400))



# test RCI
x <- all
RCI1 <- Calc_RCI_coeff(x$YEsp1, x$densite1, iso1$YEsp1/iso1$densite1)
RCI2 <- Calc_RCI_coeff(x$YEsp2, x$densite2, iso2$YEsp2/iso2$densite2)
df = data.frame(x$densite1, x$densite2, RCI1, RCI2)

RCI1[is.nan(RCI1)] <- 0.
RCI2[is.nan(RCI2)] <- 0.


plot(x$densite1, x$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=3*RCI1, main ="RCI esp 1", xlim=c(0,400), ylim=c(0,400))
plot(x$densite1, x$densite2, xlab="densite1", ylab="densite 2", pch=16, cex=3*RCI2, main ="RCI esp 2", xlim=c(0,400), ylim=c(0,400))





#####################
#####################
# test indices loreau


#test indices Loreau pour la diag
# !!valable pour 1 densite donnee!
# somme fait aOY

x <- diag
tabx <- Calc_CESE_diag(x)
tabx$CE
tabx$SE


resCE_SE <- data.frame(Semprop1=x$Semprop1, OYa=tabx$OYa, CE=tabx$CE, SE=tabx$SE)
titre <- paste(as.character(x$mix[1]), "400 ",scenar)
Plot_resCE_SE(resCE_SE, ylim=c(-400,400), type='b', ylab="OYa", xlab="Prop1", main=titre)







```



## test calcul NBE / CE /SE

```{r }


#### TansfertN
head(rmixan[,1:11])


### figure CE / SE

rmixan$RYl <- rmixan$rdtLuzasso / rmixan$rdtLuzpur
rmixan$RYg <- rmixan$rdtFetasso / rmixan$rdtFetpur
rmixan$RYTbis <- rmixan$propLuz*rmixan$RYl + (1-rmixan$propLuz)*rmixan$RYg
rmixan$RYT <- rmixan$RYl + rmixan$RYg
#? quel bon RYT?
#RY: teorique?? = proportion an n-1 / an1=0.5
rmixan$RYtheol <- 1#c(0.5, rmixan$propLuz)[1:(length(rmixan$propLuz))]#rmixan$propLuz
rmixan$RYtheog <- 1#c(0.5, 1-rmixan$propLuz)[1:(length(rmixan$propLuz))]#1-rmixan$propLuz



rmixan$rdtLuzpur+rmixan$rdtFetpur #rdmt theo
rmixan$rdtLuzasso+rmixan$rdtFetasso #rdmt vrai
ecl <- rmixan$rdtLuzasso-rmixan$rdtLuzpur #ecart theo legumineuse
ecg <- rmixan$rdtFetasso-rmixan$rdtFetpur #ecart theo graminee
ecl+ecg #somme des delta = ce que je dois trouver

#test avec Rdmt theo = somme des cultures pures
RYtheol <- rmixan$propLuzAn_1 #0.5#1
RYtheog <- 1-rmixan$propLuzAn_1 #0.5#1
deltaRYl <- rmixan$RYl - RYtheol
deltaRYg <- rmixan$RYg - RYtheog

(rmixan$RYl*rmixan$rdtLuzpur + rmixan$RYg*rmixan$rdtFetpur) - (RYtheol*rmixan$rdtLuzpur + RYtheog*rmixan$rdtFetpur)
deltaRYl*rmixan$rdtLuzpur + deltaRYg*rmixan$rdtFetpur




rmixan$deltaRYl <- deltaRYl
rmixan$deltaRYg <- deltaRYg


#vecteur CE/SE
vCE <- NULL
vSE <- NULL
for (idY in 1:dim(rmixan)[1])
{
  #idY <- 3
  
  ex_M <- as.numeric(rmixan[idY, c("rdtLuzpur","rdtFetpur")]) #rdmt en pur!!
  ex_deltaRY <- as.numeric(rmixan[idY, c("deltaRYl","deltaRYg")])
  
  CE <- Calc_CEi(2,ex_M,ex_deltaRY)
  SE <- Calc_SEi(2,ex_M,ex_deltaRY)
  vCE <- rbind(vCE, CE)
  vSE <- rbind(vSE, SE)
}

vCE + 0.5*vSE #yes, c'est bon!
rmixan$CE <- as.numeric(vCE)
rmixan$SE <- as.numeric(vSE)



############ Fig  ##################"
plot(rmixan$Coupe, (rmixan$CE+0.5*rmixan$SE), type='b',ylim=c(-800,1300), main="", ylab="Deviation from Ytheo (g.m-2)", xlab="Year of production", xlim=c(0.5,6.5), cex.lab=1.5, pch=0)
polygon(c(1.5,2.5,2.5,1.5), c(-800, -800, 1300, 1300), col="grey90", border=NA)
polygon(c(3.5,4.5,4.5,3.5), c(-800, -800, 1300, 1300), col="grey90", border=NA)
polygon(c(5.5,6.5,6.5,5.5), c(-800, -800, 1300, 1300), col="grey90", border=NA)

col1 <- rgb(0,0,1,1/4)#4
x <- c(1., 1:6, 6.)
y <- c(0, rmixan$CE,0)
polygon(x,y,col=col1)
col2 <- rgb(1,0,0,1/4)#2
y <- c(0, 0.5*rmixan$SE,0)
polygon(x,y,col=col2)
points(rmixan$Coupe, (rmixan$CE+0.5*rmixan$SE), type='b', lwd=2,pch=0)

text(1,1200,"2011")
text(2,1200,"2012")
text(3,1200,"2013")
text(4,1200,"2014")
text(5,1200,"2015")
text(6,1200,"2016")


legend(1.1,950, c("CE", "SE", "Y-Ytheo"),  lwd=c(2,2,2), pch=c(NA,NA,0), col=c(col1,col2,1),bty="n")




```



## test overyielding sur desisgn de deWit?

```{r }


#####################
#####################
# test figures deWit et indices article



# pour figure OY et OY-N 
# 

#dat <- tabtoto_compet
#names(dat)
#unique(dat$keysc)

## selectionne 1 cle et densite 400 (dispositif de substitution)
#dtoto <- dat[dat$keysc == "55-1 Fix2-nonFixSimTest Lusignan30IrrN2 -" & dat$densite== 400., ]


dtoto <- diag

#calcul tamoy (ici pas utile car 1 seul sim par densite)
tabmoy <- Build_AverageScTable(dtoto, keysc=unique(dtoto$keysc))
tabmoy

#visu plot et indices
res <- YtotvsProp(tabmoy, visuplot=T, visutext=F, supindices=F)
res

res <- YtotvsProp(tabmoy, visuplot=F, visutext=F, supindices=T)
res

resN <- QNtotvsProp(tabmoy, visuplot=T, visutext=F, supindices=F)
resN

resN <- QNtotvsProp(tabmoy, visuplot=F, visutext=F, supindices=T)
resN

```
