---
title: "plot-sim"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{plot-sim}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(RPackVGL)
library(ggplot2)
library(ggpubr)
library(pander)

```

```{r }

###### test fonction 'read_ltoto'

path_ltoto1 <- system.file("extdata", "toto_6129_l-egume_Orca-Orca_homogeneous0_scenario12-12_DigitLuz10LD_0_DigitLuz10_-_.csv", package = "RPackVGL")
path_ltoto2 <- system.file("extdata", "toto_6130_l-egume_Orca-Orca_homogeneous0_scenario12-12_DigitLuz10LD_1_DigitLuz10_-_.csv", package = "RPackVGL")
path_ltoto3 <- system.file("extdata", "toto_6131_l-egume_Orca-Orca_homogeneous0_scenario12-12_DigitLuz10LD_2_DigitLuz10_-_.csv", package = "RPackVGL")

ls_toto <- c(path_ltoto1, path_ltoto2, path_ltoto3)
my_ltoto <- read_ltoto(ls_toto)
names(my_ltoto)

```


```{r }

##### import test data
ltoto <- ltoto_exemple
names(ltoto)
#ltoto

obs <- obs_exemple
names(obs)
#obs


```



```{r }

##### moyennes des graines simulees

simmoy <- build_simmoy(ltoto, lsusm=names(ltoto))
simsd <- build_simmoy(ltoto, lsusm=names(ltoto), optSD = T)
names(simmoy)


```


```{r , results='asis'}

### test de plot

gg_plotsim("LAI", simmoy, simsd, name="test")


### ajout de points observes

plt_test <- gg_plotsim("NBI", simmoy, simsd, name="test")

# resize obs data.frame to the dim of simmoy
obsOK <- obs[obs$DOY %in% simmoy$STEPS,]
obsMerge <- simmoy[,c("STEPS","TT")]
names(obsMerge)[1] <- "DOY"
obsMerge <- merge(obsMerge, obsOK, by="DOY",all=T)

#corresponding names in sim/obs data.frames
corresp <- data.frame(sim=c("NBI","LAI","MSA"), obs=c("NBI-quart","surf_tot","MSaerien"))

#add obs points to plot
plt_test <- gg_addplotobs(plt_test, "NBI", obsMerge, corresp)
plt_test


### plot obs-sim et ajout RMSE et autres criteres d'eval
var_ <- "NBI"
nomvarobs <- as.character(corresp[corresp$sim==var_,c("obs")])
obssim <- na.omit(data.frame(obs=simmoy[,var_], sim=obsMerge[,nomvarobs]))
gg_plotObsSim(obssim, var_, name="test")



# calcul des critere d'eval
reg   <- lm(obs ~ sim, data = obssim)
coeff <- coefficients(reg)
RMSE_ <- round(rmse(obssim$obs,obssim$sim), 2)
rmses_ <- rmsesCoucheney(obssim$obs,obssim$sim)
rmse_ <- rmseuCoucheney(obssim$obs,obssim$sim)
pRMSEs_ <- round(pRMSEs(rmse_, rmses_), 2)
rRMSE <- round(rrmseCoucheney(obssim$obs,obssim$sim), 2)
EF <- round(efficiencyCoucheney(obssim$obs,obssim$sim), 2)


df <- data.frame(RMSE_, rRMSE, pRMSEs_, EF)
pander::pandoc.table(df)


### construire la liste des graphs pour ttes les variables



#correspondance des noms de variable sim/obs
corresp <- data.frame(sim=c("NBI","LAI","MSA"), obs=c("NBI-quart","surf_tot","MSaerien"))



#cree une liste ls_plt avec les figures/plot simule dans simmoy
ls_plt <- vector("list", length=length(names(simmoy)))
names(ls_plt)  <- names(simmoy)

for (var_ in names(simmoy))
{
  ls_plt[[var_]] <- gg_plotsim(var_, simmoy, simsd, name=var_)
}

ls_plt[["NBI"]]
ls_plt[["MSA"]]
ls_plt[["MSArec"]]
ls_plt[["MSAnonrec"]]
ls_plt[["MSpiv"]]
ls_plt[["MSracfine"]]
ls_plt[["NNI"]]
ls_plt[["Npc_aer"]]


### visu multi-panneau


#ajout des obs pour les variables dispo dans la liste des plot simule (liste dans corresp)
for (var_ in names(ls_plt))
{
  if (var_ %in% corresp$sim)
  {
    ls_plt[[var_]] <- gg_addplotobs(ls_plt[[var_]], var_, obsMerge, corresp)
  }
}
#ls_plt[["NBI"]]

 
#arrange gg plots en pannels
ggarrange(ls_plt[["NBI"]], ls_plt[["NBphyto"]], ls_plt[["LAI"]] + rremove("x.text"), 
           labels = c("A", "B", "C"),
           ncol = 1, nrow =3 )


ggarrange(ls_plt[["RDepth"]], ls_plt[["Hmax"]], ls_plt[["MSA"]] + rremove("x.text"),
          labels = c("A", "B", "C"),
          ncol = 1, nrow =3 )

ggarrange(ls_plt[["FTSW"]], ls_plt[["NNI"]], ls_plt[["R_DemandC_Root"]] + rremove("x.text"),
          labels = c("A", "B", "C"),
          ncol = 1, nrow =3 )


```







